export type ZoomServiceEventsType =
  | 'ZOOM-SERVICE-API/CREATE-SESSION-INFORMATION'
  | 'ZOOM-SERVICE-API/SESSION_FAILED'
  | 'ZOOM-SERVICE-API/MEETING-STARTED'
  | 'ZOOM-SERVICE-API/STREAM-OWNER-ACCEPTED-TO-MEETING'
  | 'ZOOM-SERVICE-API/STREAM-OWNER-CONNECTED-TO-MEETING'
  | 'ZOOM-SERVICE-API/SESSION_STARTED'
  | 'ZOOM-SERVICE-API/SESSION_FINISHED';
